
@host = http://localhost:8080/r4



### CDA ClinicalDocument TO FHIR Bundle

### POST CdaToFhirTypes.map

POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./maps/CdaToFhirTypes.map


### POST CdaToBundle
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./maps/CdaToBundle.map

### POST CdaChToBundle
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./maps/CdaChToBundle.map

### POST CdaChEmedMedicationCardDocumentToBundle.map 
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./maps/CdaChEmedMedicationCardDocumentToBundle.map

  
### Transform CDAMedicationCardDocument

POST {{host}}/StructureMap/$transform?source=http://hl7.org/fhir/cda/mapping/CdaChEmedMedicationCardDocumentToBundle
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ../hl7ch-cda/projects/eHealthSuisse/eMedikation/v1.0/2-7-MedicationCard.xml

Origin: 

curl --request POST \
  --url 'http://localhost:8080/r4/StructureMap/$transform?source=http%3A%2F%2Fhl7.org%2Ffhir%2Fcda%2Fmapping%2FCdaChEmedMedicationCardDocumentToBundle' \
  --header 'accept: application/fhir+xml;fhirVersion=4.0' \
  --header 'content-type: application/fhir+xml;fhirVersion=4.0' \
  -d @/Users/oliveregger/Documents/github/hl7ch-cda/projects/eHealthSuisse/eMedikation/v1.0/2-7-MedicationCard.xml > /Users/oliveregger/Documents/github/ch-emed/examples/bundle/2-7-MedicationCard-FHIR.xml



### Transform ClinicalDocument for CDA

POST {{host}}/StructureMap/$transform?source=http://hl7.org/fhir/cda/mapping/CdaToBundle
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0


< ./resources/examples/cda-ch.xml


### Transform ClinicalDocument for CdaCh

POST {{host}}/StructureMap/$transform?source=http://hl7.org/fhir/cda/mapping/CdaChToBundle
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0


< ../hl7ch-cda/projects/eHealthSuisse/eMedikation/v1.0/2-7-MedicationCard.xml

### FHIR to CDA

POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./maps/FhirtoCdaTypes.map

###

POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./maps/BundleToCda.map

###

POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./maps/BundleToCdaCh.map


### BundleToCdaChEmedMedicationCardDocument


POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./maps/BundleToCdaChEmedMedicationCardDocument.map



### Transform 2-7-MedicationCard.fhir.xml

POST {{host}}/StructureMap/$transform?source=http://hl7.org/fhir/cda/mapping/BundleToCdaChEmedMedicationCardDocument
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0


< ./resources/examples/2-7-MedicationCard.fhir.xml
